---
cassandra_cluster_name: "UnoSoftCluster"
sudo_password: "Cassandra2024!"

docker_network_subnet: "192.168.1.0/24"
docker_network_gateway: "192.168.1.1"

cassandra_nodes:
  - name: cassandra-node1
    container_ip: 192.168.1.200
    internal_ip: 172.20.0.10
    port: 9042
    ssh_port: 2201
  - name: cassandra-node2
    container_ip: 192.168.1.201
    internal_ip: 172.20.0.11
    port: 9042
    ssh_port: 2202
  - name: cassandra-node3
    container_ip: 192.168.1.202
    internal_ip: 172.20.0.12
    port: 9042
    ssh_port: 2203