[bastion]
b_server ansible_host=158.160.115.104 ansible_user=ubuntu ansible_ssh_private_key_file=/home/valar/.ssh/key_to_bastion

[cassandra]
a_server ansible_host=192.168.1.197 ansible_user=ubuntu

[cassandra:vars]
ansible_ssh_private_key_file=/home/valar/.ssh/bastion_to_cluster_key

ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/valar/.ssh/key_to_bastion -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@158.160.115.104"'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_args="-o ControlMaster=no -o ControlPersist=no -o StrictHostKeyChecking=no"


