---
- name: Configure Bastion (Proxy)
  hosts: bastion
  become: yes
  gather_facts: yes
  roles:
    - role: tinyproxy

- name: Configure Cassandra Nodes (Docker + Cluster)
  hosts: cassandra
  become: yes
  gather_facts: yes
  roles:
    - role: docker
    - role: cassandra-cluster
